"""init

Revision ID: 0fa97c48f514
Revises: 
Create Date: 2026-04-22 00:19:15.616382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa97c48f514'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_juego',
    sa.Column('id_catJuego', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_catJuego')
    )
    op.create_table('categoria_producto',
    sa.Column('id_catProducto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_catProducto')
    )
    op.create_table('mesa',
    sa.Column('id_mesa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_mesa')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('juego',
    sa.Column('id_juego', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('precio_alquiler', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('disponible_venta', sa.Boolean(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('categoria_juego_id_catJuego', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_juego_id_catJuego'], ['categoria_juego.id_catJuego'], ),
    sa.PrimaryKeyConstraint('id_juego')
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('max_personas', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('categoria_producto_id_catProducto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_producto_id_catProducto'], ['categoria_producto.id_catProducto'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pregunta_seguridad', sa.String(length=255), nullable=False),
    sa.Column('respuesta_seguridad', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('rol_id_rol', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['rol_id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('usuario_id_usuario', sa.Integer(), nullable=False),
    sa.Column('mesa_id_mesa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id_mesa'], ['mesa.id_mesa'], ),
    sa.ForeignKeyConstraint(['usuario_id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('registro_actividad',
    sa.Column('id_registro_actividad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_registro_actividad')
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('usuario_id_usuario', sa.Integer(), nullable=False),
    sa.Column('mesa_id_mesa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id_mesa'], ['mesa.id_mesa'], ),
    sa.ForeignKeyConstraint(['usuario_id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_table('detalle_pedido',
    sa.Column('id_detallePed', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('producto_id_producto', sa.Integer(), nullable=False),
    sa.Column('pedido_id_pedido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['producto_id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detallePed')
    )
    op.create_table('detalle_reserva',
    sa.Column('id_detalleReserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('producto_id_producto', sa.Integer(), nullable=False),
    sa.Column('reserva_id_reserva', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id_producto'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['reserva_id_reserva'], ['reserva.id_reserva'], ),
    sa.PrimaryKeyConstraint('id_detalleReserva')
    )
    op.create_table('registro_juego',
    sa.Column('id_regJuego', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('juego_id_juego', sa.Integer(), nullable=False),
    sa.Column('usuario_id_usuario', sa.Integer(), nullable=False),
    sa.Column('reserva_id_reserva', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['juego_id_juego'], ['juego.id_juego'], ),
    sa.ForeignKeyConstraint(['reserva_id_reserva'], ['reserva.id_reserva'], ),
    sa.ForeignKeyConstraint(['usuario_id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_regJuego')
    )
    op.create_table('pago',
    sa.Column('id_pago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('detalle_pedido_id_detallePed', sa.Integer(), nullable=False),
    sa.Column('detalle_reserva_id_detalleReserva', sa.Integer(), nullable=False),
    sa.Column('registro_juego_id_regJuego', sa.Integer(), nullable=False),
    sa.Column('usuario_id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detalle_pedido_id_detallePed'], ['detalle_pedido.id_detallePed'], ),
    sa.ForeignKeyConstraint(['detalle_reserva_id_detalleReserva'], ['detalle_reserva.id_detalleReserva'], ),
    sa.ForeignKeyConstraint(['registro_juego_id_regJuego'], ['registro_juego.id_regJuego'], ),
    sa.ForeignKeyConstraint(['usuario_id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('registro_juego')
    op.drop_table('detalle_reserva')
    op.drop_table('detalle_pedido')
    op.drop_table('reserva')
    op.drop_table('registro_actividad')
    op.drop_table('pedido')
    op.drop_table('usuario')
    op.drop_table('producto')
    op.drop_table('juego')
    op.drop_table('rol')
    op.drop_table('mesa')
    op.drop_table('categoria_producto')
    op.drop_table('categoria_juego')
    # ### end Alembic commands ###
